# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 847e45d22cafa10a5d6366b01a82c49cdcaefb954553e880668cacc6d82e4d760ddd413539fb66a24ecc88d2bbb889f5081f3a7201555f45736dd2126688eae0

test:
  secret_key_base: c07e42ef56f55ac1ecb047636dea67066a7ef18e060a58c88a9d3af63d9ba0448f8c767a5f6b7308994f56a4c1b7475485605ba5bc43a56f91d3b69afce30441

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
